from django.contrib import admin
from scenario.models import *

admin.site.register(Scenario)
admin.site.register(Plan)
admin.site.register(PlanBudget)
admin.site.register(IncomeItemInflationRate)
admin.site.register(CostItemInflationRate)
admin.site.register(CurrentLoans)
admin.site.register(FinanceAnalysis)
admin.site.register(BalanceSheet)
admin.site.register(Inflation)
admin.site.register(IncomeStatement)
admin.site.register(CapitalLease)
admin.site.register(Distributions)
admin.site.register(CapitalPurchase)
admin.site.register(Depreciations)
admin.site.register(AccrualAdjustments)
admin.site.register(CashFlowItem)
admin.site.register(FutureCapitalLease)
admin.site.register(CashflowPdfOutput)
admin.site.register(CashflowPdfOutputItem)
admin.site.register(BalanceSheetOutput)
admin.site.register(BalanceSheetOutputItem)
admin.site.register(IncomeStatementOutput)
admin.site.register(IncomeStatementOutputItem)
admin.site.register(FinancialRatiosOutput)
