TIME_UNITS = (
    ("Year","Year(s)"),
    ("Month","Month(s)"),
    ("Week","Week(s)"),
    ("Day","Day(s)"),
)
FARM_UNITS = (
    ('Total', 'Total'),
    ('Acre', 'Acre(s)'),
    ('Sq. Feet', 'Sq. Feet'),
    ('Field', 'Field(s)'),
    ('Ton', 'Ton(s)'),
    ('Pound', 'Pound(s)'),
    ('Cwt', 'Cwt(s)'),
    ('Box', 'Box(es)'),
    ('Bottle', 'Bottle(s)'),
    ('Case', 'Case(s)'),
    ('Herd', 'Herd(s)'),
    ('Head', 'Head(s)'),
    ('Cow', 'Cow(s)'),
    ('Flock', 'Flock(s)'),
)
SALE_UNITS = (
    ('Total', 'Total'),
    ('Ton', 'Ton(s)'),
    ('Pound', 'Pound(s)'),
    ('Bushel', 'Bushel(s)'),
    ('Bin', 'Bin(s)'),
    ('Cwt', 'Cwt(s)'),
    ('Tree', 'Tree(s)'),
    ('Lbs', 'Lbs(s)'),
    ('Carton', 'Carton(s)'),
    ('Head', 'Head(s)'),
    ('Herd', 'Herd(s)'),
    ('Box', 'Box(es)'),
    ('Acre', 'Acre(s)'),
    ('Bale', 'Bale(s)'),
    ('Case', 'Case(s)'),
    ('Bag', 'Bag(s)'),
    ('Sack', 'Sack(s)'),
    ('Bottle', 'Bottle(s)'),
)